### ISSUE TITLE
Useless use of cat

### ISSUE THREAD

**Issue by cirosantilli** [catern/dotfiles#1]
```
cat ~/.config/dconf/user.d/* | dconf load /
```

https://github.com/catern/dotfiles/tree/master/home/.config/dconf/user.d

:-)

**Comment by catern** [comment]
How else do you propose doing that? I need to concatenate several files into a single stream which I send to dconf; that is exactly what cat is for.

**Comment by cirosantilli** [comment]
Lol, where do I hide in my shame.
